<!DOCTYPE HTML>
<html>
    <head>
        <title>Đăng nhập vào quản trị</title>
        <meta charset="UTF-8" />
        <link rel="stylesheet" type="text/css" href="<?php echo STATIC_URL . '/b/css/bootstrap.min.css'; ?>">
        <link rel="stylesheet" type="text/css" href="<?php echo STATIC_URL . '/b/css/bootstrap-reset.css'; ?>">
        <link rel="stylesheet" type="text/css" href="<?php echo STATIC_URL . '/b/css/style.css'; ?>">
        <link rel="stylesheet" type="text/css" href="<?php echo STATIC_URL . '/b/css/style-responsive.css'; ?>">
        <style>body, label, .form-signin h2.form-signin-heading{font-family:"Times New Roman",Georgia,Serif !important;}</style>
    </head>

    <body class="login-body">
        <?php echo $this->layout()->content; ?>
    </body>
</html>
