<!DOCTYPE html>
<html>
    <head>
        <link href="http://dev.st.abc.vn/b/css/??bootstrap.min.css,bootstrap-reset.css,font-awesome.min.css,font-awesome-animation.min.css,style.css,style-responsive.css,custom.css,table-responsive.css,pnotify.custom.min.css?v=1459150412" media="screen" rel="stylesheet" type="text/css">
        <link href="http://dev.st.abc.vn/b/css/sumoselect.css?v=1459235094" media="screen" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="http://dev.st.abc.vn/b/js/library/??jquery-1.11.3.min.js,bootstrap.min.js,jquery.dcjqaccordion.2.7.js,jquery.scrollTo.min.js,jquery.nicescroll.js,respond.min.js,bootbox.min.js,moment-with-langs.min.js,pnotify.custom.min.js,common-scripts.js,jquery.validate.min.js,jquery.inputmask.bundle.min.js,jquery.sumoselect.min.js?v=1459235094"></script>
        <script type="text/javascript" src="http://dev.st.abc.vn/b/js/my/user.js"></script>        
        <script type="text/javascript">
            var baseUrl   = 'http://dev.abc.vn';
            var staticUrl = 'http://dev.st.abc.vn';
            var fullname  = 'Pham Toan';
            var role      = '1';
            var email     = 'admin@microlink.vn';
        </script>
    </head>
    <body>
        <section id="container" class="sidebar-closed">
            <?php
            echo $this->render('adminuser/header');
            echo $this->render('adminuser/sidebar');
            ?>
            <section id="main-content"><?php echo $this->layout()->content; ?></section>
            <footer class="site-footer">
                <div class="text-center">
                    2016 &copy; Fado.VN
                    <a href="#" class="go-top">
                        <i class="fa fa-angle-up"></i>
                    </a>
                </div>
            </footer>
        </section>
        
    </body>
</html>