<div class="container">
    <div class="row">
		<div class="panel panel-default">
		  	<!-- Default panel contents -->
		  	<div class="panel-heading">
		  		<span class="pull-left"><h4>Danh sách các Form đã tạo</h4></span>
		  		<span class="pull-right"><button class="btn btn-info" id="addNew" type="button">Add New Form</button></span>
		  		<div class="clearfix"></div>
		  	</div>
		  	<!-- Table -->
		  	<table class="table">
		    	<thead>
		    		<tr>
		    			<th><input type="checkbox" id="selectall" name="inputCheck[]" ></th>
		    			<th>Tên Form</th>
		    			<th>Created date</th>
		    			<th>Created by</th>
		    			<th>ID</th>
		    		</tr>
		    	</thead>
		    	<tbody>
		    		<?php 
		    			$list = '';
		    			if(!empty($listForm)){
		    				foreach ($listForm as $key => $form) {
		    				$list .= '<tr>';
		    					$list .= sprintf(
		    							'<td><input type="checkbox" class="second" name="inputCheck[]" ></td>
		    							 <td>%s</td>
		    							 <td>%s</td>
		    							 <td>%s</td>
		    							 <td>%s</td>',$form['name'],date('d-m-Y',$form['created_date']),$form['username'],$form['id']);
		    				$list .= '</tr>';
		    				}
		    			}else{
		    				$list =  "<h3>Chưa có Form được tạo</h3>";
		    			}

		    			echo $list;
		    		?>
		    	</tbody>
		  	</table>
		</div>
    </div>
</div>

<script type="text/javascript">
	$(document).ready(function() {
		
		$("#addNew").click(function(){
			window.location.href = "<?php echo $this->url("code") ?>" ;
		})
		
		$(".second").click(function() {
			$("#selectall").prop("checked", false);
		});
		
		$("#selectall").click(function() {
			$(".second").prop("checked", $("#selectall").prop("checked"))
		})


});
</script>
