<section class="wrapper site-min-height">
    <div class="row">
        <?php echo $this->flashMessenger()->render() ?>
        <div class="col-lg-12">
            <section class="panel panel-primary">
                
                <div class="panel-body">
                    <section id="flip-scroll">
                        <table class="table table-bordered table-striped table-condensed cf">
                            <thead class="cf">
                                <tr>
                                    <th>Họ Và Tên</th>
                                    <th>Email</th>
                                    <th>Địa chỉ</th>
                                    <th style="text-align:center;">Số ĐT</th>
                                    <th style="text-align:center;">Nhóm</th>
                                    <th style="text-align:center;">Chức năng</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                if ($this->items):
                                    foreach ($this->items as $item):
                                ?>
                                        <tr>
                                            <td>
                                                <a class="tooltips" data-placement="top" data-original-title="Xem thông tin người dùng" href="<?php echo $this->serverUrl() . $this->Url('admincp', array('controller' => 'user', 'action' => 'view', 'id' => $arrUser['user_id'])); ?>">
                                                    <?php echo $item['fullname']; ?>
                                                </a>
                                            </td>
                                            <td><?php echo $item['email']; ?> </td>
                                            <td><?php echo $item['address']; ?> </td>
                                            <td style="text-align:center;"><?php echo $item['phone']; ?></td>
                                            <td style="text-align:center;">
                                                <?php echo $item['group_name'] ?>
                                            </td>
                                            <td style="text-align:center;">
                                                <a href="<?php echo $this->serverUrl() . $this->url('home/default',array('action' => 'add' , 'id' => $item['user_id']))?>" class="fa fa-pencil action tooltips edit" data-placement="top" data-original-title="Sửa thông tin"></a>
                                                <a  href="<?php echo $this->serverUrl() . $this->url('home/default',array('action' => 'destroy' , 'id' => $item['user_id']))?>" class="fa fa-times-circle tooltips action remove" data-placement="top" data-original-title="Xóa người dùng"></a>     
                                            </td>                                           
                                        </tr>

                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <tr><td colspan="6" style="text-align:center;">Hiện tại chưa có người dùng nào.</td></tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </section>
                </div>
                <div style="padding-top: 15px;">
                    <?php echo $this->paging; ?>
                </div>
            </section>

        </div>
    </div>
</section>