
<div class="container">
	<h1>[<?php echo $infoForm->name ?>]</h1>
	<br/>
	<div class="row box" id="addNameForm">
		<div class="col-md-12">
			<div class="row">

				<div class="col-md-6">
					<div class="form-group">					
						<label for="type">Name Class Form</label>
						<input type="text" width="360" value="" class="form-control" name="inputNameClassForm" />
						<!-- class="hide alert alert-danger alert-dismissable" -->
						<p class="hide text-danger" id="errorClassForm">
                        	Nhập tên Class Form để tiếp tục !
                        </p>
					</div>
				</div>		
				<div class="col-md-6">
					<div class="form-group">					
						<label for="type">Name Class Filter</label>
						<input type="text" value="" class="form-control" name="inputNameClassFilter"/>
						<!-- class="hide alert alert-danger alert-dismissable" -->
						<p class="hide text-danger" id="errorClassFilter">
                        	Nhập tên Class Filter để tiếp tục !
                        </p>
					</div>
				</div>			
				
			</div>
		</div>
		<div class="col-md-4 col-md-offset-5">
		 	<div class="form-group">
		 		<label>&nbsp;</label><br/>
		    	<button class="btn btn-primary" type="button" id="createForm">Create Form</button>
		    </div>
		</div>
	</div>
	<div class="row box viewCode hide">
		<!-- CODE FOR CLASS FORM -->
		<div class="col-md-6 ">
			<h3>Code For Class Form</h3>
			<div  name="code" class="form-control code">
				<code>
					<span class="php-keyword">namespace</span> <span class="php-plain name-space">;</span><br/>
					<br/>
					<span class="php-keyword">use</span> <span class="php-plain">Zend\Form\Form;</span><br/>
					<br/>
					<span class="php-keyword">class</span> <span class="php-plain class-form-name"></span> <span class="php-keyword">extends</span> <span class="php-plain">Form{</span><br/>
					<br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">public function</span>  <span class="php-plain">__construct() {</span><br/>
							<?php echo str_repeat("&nbsp;",10) ?><span class="php-plain">parent::__construct();</span><br/><br/>
					<div style="margin-left: 75px;">
							<?php echo $this->codeInput ?>
					</div>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-plain">)</span>
				</code><br/>
			</div>
		</div>
		<!-- END CODE FOR CLASS FORM -->

		<div class="col-md-6 ">
			<h3>Code For Class Filter</h3>
			<div  name="code" class="form-control code">
				<code>
					<span class="php-keyword">namespace</span> <span class="php-plain name-space">AutoCode\Form;</span><br/>
					<br/>
					<span class="php-keyword">use</span> <span class="php-plain">Zend\InputFilter\InputFilter;</span><br/>
					<br/>
					<span class="php-keyword">class</span> <span class="php-plain class-validate-filter-name"></span> <span class="php-keyword">extends</span> <span class="php-plain">InputFilter{</span><br/>
					<br/>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-keyword">public function</span>  <span class="php-plain">__construct() {</span><br/>
							<?php echo str_repeat("&nbsp;",10) ?><span class="php-plain">parent::__construct();</span>
					<div style="margin-left: 75px;">
							<?php echo $this->codeValidateAndFilter ?>
					</div>
					<?php echo str_repeat("&nbsp;",5) ?><span class="php-plain">)</span>
				</code><br/>
			</div>
		</div>

		<div class="col-md-6">
			<h3>Code For Action(Controller)</h3>
			<div  name="code" class="form-control code">

			</div>
		</div>

		<div class="col-md-6">
			<h3>Code For View</h3>
			<div  name="code" class="form-control code">

			</div>
		</div>
	</div>
</div>

<script>
	$("document").ready(function(){
		$("#createForm").on("click",function(){
			flag  = true;
			if($("[name=inputNameClassForm]").val() === ""){
				$("#errorClassForm").removeClass("hide");
				flag = false;
			}else{
				$("#errorClassForm").addClass("hide");
				var arr = $("[name=inputNameClassForm]").val().split("\\");
				$(".class-form-name").text(arr.pop());
				$(".name-space").eq(0).text(arr.join("\\") + ";");
				flag = true;
			}

			if($("[name=inputNameClassFilter]").val() === ""){
				$("#errorClassFilter").removeClass("hide");
				flag = false;
			}else{
				$("#errorClassFilter").addClass("hide");
				var arr = $("[name=inputNameClassFilter]").val().split("\\");
				$(".class-validate-filter-name").text(arr.pop());
				$(".name-space").eq(1).text(arr.join("\\") + ";");
				flag = true;
			}

			if(flag){
				$(".viewCode").removeClass("hide");
			}else{
				$(".viewCode").addClass("hide");
			}
		})
	})
</script>
