
<?php $urlActionValidateForm = BASE_URL. $this->url('code/default',['action' => 'validate']) ?>
<div class="container">
	<form id="validateForm" method="post" action ="<?php echo $urlActionValidateForm ?>">
		<div class="row box" id="addNew">
			<div class="col-md-12">
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">					
						    <label for="type">Type</label>
						    <select class="form-control" name="typeElement" id="typeElement">
						    	<option value="button">Button</option>
						    	<option value="checkbox">Checkbox</option>
						    	<option value="color">Color</option>
						    	<option value="date">Date</option>
						    	<option value="datetime">Datetime</option>
						    	<option value="dateime-local">Datetime-local</option>
						    	<option value="email">Email</option>
						    	<option value="file">File</option>
						    	<option value="hidden">Hidden</option>
						    	<option value="image">Image</option>
						    	<option value="month">Month</option>
						    	<option value="number">Number</option>
						    	<option value="password">Pasword</option>
						    	<option value="radio">Radio</option>
						    	<option value="range">Range</option>
						    	<option value="reset">Reset</option>
						    	<option value="search">Search</option>
						    	<option value="Submit">Submit</option>
						    	<option value="Tel">Tel</option>
						    	<option value="text">Text</option>
						    	<option value="time">Time</option>
						    	<option value="url">Url</option>
						    	<option value="week">Week</option>
						    </select>
					    </div>
					 </div>
					 
					 <div class="col-md-4">
					 	<div class="form-group">
					    	<label for="name">Name</label>
					    	<input type="text" id="nameElement" name="nameElement" class="form-control"/>
					    </div>
					 </div>
					 
					 <div class="col-md-4">
					 	<div class="form-group">
					 		<label>&nbsp;</label><br/>
					    	<button class="btn btn-primary" type="button" id="addNewElement">Add new element</button>
					    </div>
					 </div>
				    	
				</div>
				
			</div>
		</div>
	
		<div class="row box hide" id="elementAttrs">
		
			<div class="col-md-6">
				<h3> [...] Element</h3>
				<div class="row">
					<div class="col-md-4">
						<div class="form-group">					
						    <label for="id">ID</label>
						    <input type="text" id="idElement" name="idElement" class="form-control"/>
					    </div>
					 </div>
					 
					 <div class="col-md-4">
					 	<div class="form-group">
					    	<label for="class">Class</label>
					    	<input type="text" id="classElement" name="classElement" class="form-control"/>
					    </div>
					 </div>
					 
					 <div class="col-md-4">
					 	<div class="form-group">
					 		<label for="placeElement">Placeholder</label><br/>
					    	<input type="text" name="placeElement" id="placeElement" class="form-control"/>
					    </div>
					 </div>
					 
					 <div class="col-md-4">
					 	<div class="form-group">
					 		<label for="valueElement">Value</label><br/>
					    	<input type="text" name="valueElement" id="valueElement" class="form-control"/>
					    </div>
					 </div>
					 
					 <div class="col-md-4">
					 	<div class="form-group">
					 		<label for="attrElement">Attributes</label><br/>
					    	<textarea class="form-control" name="attrElement" placeholder="onclick : function()" id="attrElement" cols="30" rows="5"></textarea>
					    </div>
					 </div>
					 
				</div>
				<hr />
				<div class="row">
				<!-- List Validate Hidden For Submit -->
				<div id="listValidateHidden"></div>
				<!-- End Validate Hidden -->

					 <div class="col-md-8">
					 	<div class="form-group">
					 		<label for="validateElement">Validate</label><br/>
					    	<select name="validateElement" id="validateElement" class="form-control">
					    		<?php
					    			
					    		 	$list = "<option value='not-validate'>Choose Validate Type</option>";
					    		 	foreach($this->validateElement as $vali){
					    		 		$list .= '<option value="'. strtolower($vali['name']) .'">'. $vali['name'] .'</option>';
					    		 	}
					    		 	echo $list;
					    		 ?>
					    	
					    	</select>
					    </div>
					    

					    <ul id="validateList">
					    	
					    </ul>
					    <span class="hide" id="haveTemplate">no</span>
					    <!-- template validate option -->
					    <div id="showtemplate" class="col-md-12 validate-template">
					    	
						    
					    </div>  
					    <!-- END template validate option -->  
					    
					 </div>
					 
					 <div class="col-md-4">
					 	<div class="form-group ">
					 		<label>&nbsp;</label><br/>
					    	<button class="btn btn-primary" type="button" id="setValidate">Set validate</button>
					    </div>
					 </div> 
					 
				</div>
				
			</div>

			<div class="pull-right col-md-6 display-code">
				<h3>Code</h3>
				<textarea  name="code" id="code" cols="65" rows="20" class="form-control"></textarea>
			</div>
			 <!-- onclick="submitValidateForm()" -->
			<div class="col-md-6 col-md-offset-3 text-center">
				<button class="btn btn-primary" onclick="submitValidateForm()" id="create">Create</button>
			</div>
		
		</div>
	</form>
	
</div>
<?php $url = $this->url('code/default',array('action' => 'loadTemplate')) ?>
<script type="text/javascript">
	$(document).ready(function(){
		var nameElement,typeElement;
		$("#addNewElement").on("click",function(){
			nameElement = $("#nameElement").val();
			typeElement = $("#typeElement").val();
			
			//show form Add Atrributes Element
			$("#elementAttrs").removeClass("hide");
			changeIdInput(nameElement);			
		})
		
		$("#setValidate").on("click",function(){
		    var validateValue = $("#validateElement :selected").val();
		    var validateName  = $("#validateElement :selected").text();
		   	var fileName      = validateValue.replace('#','') + '.php';
			
		   	$.ajax({
				url  	 : "<?php echo BASE_URL .  $url ?>",
				data 	 : { fileName : fileName },
				type 	 : 'GET',
				dataType : 'json',
				success  : function(data){
					if(data.template === 'no'){
						$("#haveTemplate").text('no');
					}else{
						$("#haveTemplate").text('yes');	
						var templateFormated = data.template.replace(/my_element/g,nameElement);
						$("#showtemplate").append(templateFormated);
					}

					var haveTemplate = $("#haveTemplate").text();

		    		addValidateRow("#validateList",validateValue,validateName,nameElement,haveTemplate);

		    		$(".removeVal").on('click',function(){
					    removeOption(this);
					})

				    $(".show-option-validate").on('click',function(){
					    var self = this;
					   	var idTemplate = $(self).attr('href');
					   
					    showValidateTemplate('.show-option-validate',idTemplate);
						
						$(".cancel").on('click',function(){
							hideValidateTemplate('.show-option-validate',idTemplate);

							return false;
						})

						$(".accept").on('click',function(){
			
							var str = $(idTemplate).serialize();	

							createSerializeString(self,str)		
							hideValidateTemplate('.show-option-validate',idTemplate);

							self = null;

							return false;
						})
							
					})
							
				},
			})		 	
		})

	})

	function submitValidateForm(){
		$("#validateForm").submit();

	}

	function createSerializeString(selector,str){
		createRowValidateHidden(str);
		
		serializeString = createPrettySerializeString(str);

		$(selector).next().next().removeClass('hide').html(serializeString);
	}

	function createPrettySerializeString(str){
		
		str = str.replace(/([^(%5BD\s)])/g,function(match,p1,p2,p3){
				if(match === '&') {
					return '<span class="blue">' + match + '</span>';
				}else{
					return '<span class="red">' + match + '</span>';
				}
			});

		return str;
	}

	function addValidateRow(selector,validateValue,validateName,nameElement,haveTemplate){
		$(selector).append(addOptionValidate(validateValue,validateName,nameElement,haveTemplate) );
	}

	function removeOption(selector){	
		$(selector).parents('li').remove();
		var idTemplate = $(selector).prev('a').attr('href');
		$(idTemplate).remove();
	}


	function createRowValidateHidden(str,haveTemplate = 'yes'){
		if(haveTemplate === 'yes'){
			var newArr = str.split('&');
			$.each(newArr,function(index,val){
				val = val.replace(/%5B/g,'[');
				val = val.replace(/%5D/g,']');
				var option = val.split('=');
				$("#listValidateHidden").append('<input type="hidden" name="' + option[0] + '" value="' + option[1] + '" />')
			})
		}else if(haveTemplate === 'no'){
			$("#listValidateHidden").append('<input type="hidden" value="' + str[1] + '" name="' + str[0] +'[validateName][]">');
		}
		
	}

	function addOptionValidate(validateValue,validateName,nameElement,haveTemplate){
		var str = [nameElement,validateValue];
		createRowValidateHidden(str,'no');

		if(haveTemplate === 'yes'){
			return '<li><a class="show-option-validate" href="#' + validateValue + '">' + validateName + '</a> <span class="removeVal glyphicon glyphicon-remove"></span> <i class="hide"></i></li>';
		}else{
			return '<li>' + validateName + '<span class="removeVal glyphicon glyphicon-remove"></span></li>';
		}
	}
	
	function changeIdInput(nameElement){
		$("#elementAttrs h3:first").text("[" + nameElement + "] Element")
		$("#idElement").attr('name',nameElement + "[id]");
		$("#classElement").attr('name',nameElement + "[class]");
		$("#placeElement").attr('name',nameElement + "[placeholder]");
		$("#valueElement").attr('name',nameElement + "[value]");
		$("#attrElement").attr('name',nameElement  + "[attr]");
	}
	
	function showValidateTemplate(selector,idTemplate){
		$(selector).parents("ul#validateList").hide();
		$(idTemplate).addClass("animated fadeIn").removeClass('hide')
	}
	
	function hideValidateTemplate(selector ,idTemplate){
		$(selector).parents("ul#validateList").show();
		$(idTemplate).removeClass("animated fadeIn").addClass('hide')
	}
	
</script>